# Generated by Django 4.2.3 on 2023-08-02 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_category_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Posted', 'Posted'), ('Unposted', 'Unposted')], default='Posted', max_length=200, verbose_name='Status'),
        ),
    ]
