# Generated by Django 4.2.3 on 2023-08-02 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_category_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(blank=True, to='core.category', verbose_name='Категории'),
        ),
    ]
