# Generated by Django 4.2.3 on 2023-08-17 05:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0012_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='short',
            name='viewed_users',
            field=models.ManyToManyField(blank=True, related_name='viewed_shorts', to=settings.AUTH_USER_MODEL),
        ),
    ]
