# Generated by Django 4.2.3 on 2023-08-17 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_short_viewed_users'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='link_fb',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='photo',
            field=models.ImageField(null=True, upload_to='profile_photo/'),
        ),
    ]
